name: Automatic Gradle Wrapper Upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  upgradeGradleWrapper:
    runs-on: ubuntu-latest
    env:
      WRAPPER_UPGRADE_GIT_TOKEN: ${{ secrets.MY_GH_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup git
        run: |
          git config --global user.email "your.email@gmail.com"
          git config --global user.name "Your name"
          git config --global url."https://unused-username:${WRAPPER_UPGRADE_GIT_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Upgrade Gradle Wrapper
        run: ./gradlew upgradeGradleWrapperProjectCore
